apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.111
    path: /volume1/cozy/data
