host: 0.0.0.0 
port: 8080

admin:
  host: localhost 
  port: 6060
  secret_filename: cozy-admin-passphrase

couchdb:
#  url: http://couchdb:5984
  url: 'http://{{.Env.COUCHDB_USERNAME}}:{{.Env.COUCHDB_PASSPHRASE}}@couchdb:5984/'
subdomains: nested 

fs:
  url: file://localhost/var/lib/cozy

vault:
  credentials_encryptor_key: /etc/cozy/keys/vault.enc
  credentials_decryptor_key: /etc/cozy/keys/vault.dec

konnectors:
#  cmd: /usr/share/cozy/konnector-nsjail-run.sh

log:
  level: debug
  syslog: false

mail:
  host: smtp 
  port: 1025 
  disable_tls: true 
  skip_certificate_validation: true 

registries:
  default:
  - https://apps-registry.cozycloud.cc/selfhosted
  - https://apps-registry.cozycloud.cc/banks
  - https://apps-registry.cozycloud.cc/


